### PR TITLE
Option to set IID subsample

### PR DESCRIPTION
**Pull request by handwerkerd**
As discussed at the May 2023 tedana developers call, we decided to add an option to let a user set the IID subsampling value `sub_iid_sp_median` I think this PR has it working, but I want to make sure everything is correct and properly documented before saying it's ready to merge.

As part of this PR, we'll always estimate the IID subsample and both the estimated IID subsample and the one used (different if user provided) will be logged.

### CODE REVIEW

**Comment by handwerkerd** [comment]
I cleaned up the code & documentation and fixed an existing bug that was causing integration tests to fail (A file name was mistyped). If we decide this option is worth adding, this PR is ready for review/merging.

**Comment by handwerkerd** [comment]
The new figure includes spatial smoothness from each run (AFNI's `3dFWHMx`) 
Rows 1 & 2: number of components vs variance explained (Row 1 was in my previous comment)
Rows 3 & 4: number of components vs FWHM
Rows 5 & 6: variance explaiend vs FWHM
The odd rows are colored by the estimated subsampling depth (same as in my previous comment) and the even rows are colored by subject number to see if this is a subject-specific effect.

The issues are definitely in some subjects more than others and there's one subject with a larger FWHM than others, but the component estimates in that subject are typical and the estimated subsampling depth was 2.  
Subsampling depth of 3 is definitely a couple of subjects with higher FWHM vals, but not the highest vals. 
Subsampling depth of 1 is in runs with lower FWHM than others, but still within the group.

There's something here, but I don't think it's as simple as a FWHM->dimensionality estimate mapping.

I don't think this PR fully solves the issue, but I do think it might be useful.
comps_fwhm

**Comment by eurunuela** [comment]
Hey @dowdlelt, have you had the chance to test it?

I lean towards merging this PR.

**Review by dowdlelt — APPROVED** [review]
I've found some good data to play with, but in the meantime, looks good to me. Happy subsampling!

**Review by dowdlelt — APPROVED** [review]

**Comment by dowdlelt** [comment]
@eurunuela - I don't think you ever actually approved this, came up in the meeting today. Assuming you approve, we should be good to go.

**Comment by eurunuela** [comment]
Sorry @dowdlelt, I do approve.

Didn't know we had a meeting!

**Review by dowdlelt — APPROVED** [review]
Github confuses me - maybe because I wasn't requested my previous reviews didn't count? Do it live I say!

(but really, should be good to go)

**Pull request merged**
