### PR TITLE
Change `n_features_` to `n_features_in_` for sklearn compatibility

### LINKED ISSUE #58: `n_features_` from sklearn's PCA is deprecated
`n_features_` from sklearn's PCA is deprecated and has to be updated to `n_features_in_`.

```python
/export/home/mflores/.conda/envs/tedana/lib/python3.9/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute `n_features_` was deprecated in version 1.2 and will be removed in 1.4. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)
```

### PR DESCRIPTION
**Pull request by eurunuela**
Closes #58.

This PR proposes:

- Change `n_features_` for `n_features_in_` to be compatibly with sklearn.
- ~Adds dependencies to the package (apparently they were not there).~
- Updates the necessary scikit-learn version to at least 1.2.

### CODE REVIEW

**Comment by eurunuela** [comment]
We may want to drop support for 3.5 and add tests for up to 3.10 or so.

**Comment by eurunuela** [comment]
I will open a new PR to work on the `project.toml` and update the minimum Python version for the package (needs to be at least 3.8).

**Comment by eurunuela** [comment]
It looks like @tsalo may be busy, @handwerkerd would you mind reviewing this? It's impacting tedana for users with a newer version of `scikit-learn`.

**Review by handwerkerd — APPROVED** [review]
LGTM

Flake8 seems to be really unhappy with a bunch of stuff so you might want another PR to run updated Black on the code.

Also, I'm generating a local `_version.py` file which says it shouldn't be tracked with version control, but it's not in `.gitignore` I'm not sure if this is a standing quirk or something that's a new issue. Either way, it's separate from the problem this PR is trying to correct.

**Comment by handwerkerd** [comment]
@eurunuela Will we also need to update the minimum mapca version in tedana to fully address this sklearn compatibility issue? It's [currently mapca>=0.0.3](https://github.com/ME-ICA/tedana/blob/b6c53fcfe34c98f6ff4f2afd0f0f0d5e8ac66c38/pyproject.toml#L25) and I think this will now be mapca 0.0.5.

**Comment by handwerkerd** [comment]
With this and #64 merged, I think you can cut a release whenever you have time and then we can bump up the minimum mapca version in tedana.

**Pull request merged**
