### PR TITLE
Updating style and python versions

### LINKED ISSUE #63: Black and isort need to be rerun

### PR DESCRIPTION
**Pull request by handwerkerd**
Closes #63
- Fixes new Flake8 style issues
- Adds python 3.11 and 3.12 to `pyproject.toml`
- Add unit tests for python 3.11 and 3.12 to `config.yml` (First time I've done this so make sure I didn't mess anything up)
- I tried updating the orb version for codecov in `config.yml`, but it messed something up so I changed it back.

The Flake8 issues were slightly more annoying than just running `Black`. Most were things like removing capital letters from variable names and cleaning up docstrings. Most variable name changes were simple, but one was confusing. `Lambda` needed the capital letter removed, but `lamba` has other meanings so I changed it to `lamba_var`. Also I had to change all `print` statements with `.format()` or `%` to f-strings.

There are two style issues I haven't solved yet:
- `__init__.py` has a relative import of `.mapca` and just changing that to `mapca` doesn't seem to solve it.
- https://github.com/handwerkerd/mapca/blob/1ce539216d37732e4a0cbf5d3c9101117cf35410/mapca/mapca.py#L482 Has an unused argument `img`. I can fix this one, but wanted to make sure this isn't a sign something else is wrong.

### CODE REVIEW

**Comment by eurunuela** [comment]
Thank you @handwerkerd.

I will have a look later today.

**Comment by eurunuela** [comment]
Okay, so I don't know how we can fix the circular import issue to avoid using the relative import.

Do you think it's a critical change @handwerkerd?

I have already removed the unused `img` variable from `transform()`.

**Comment by handwerkerd** [comment]
I'm not sure. Locally I'm seeing the error `Relative import found Flake8(ABS101)`. It's passing the CircleCI style_check so we don't need to solve this now, but it might be an issue in the near-ish future. `tedana` doesn't have anything like this in its `__init__.py` so maybe there's a way it's not necessary. When I just got rid of it, problems arose, so it's not that simple.

In checking stuff, I also noticed I didn't update the testing files for style errors & that's fixed in the most recent push (along with added `_version.py` to `.gitignore`

**Comment by handwerkerd** [comment]
I do see one issue locally that might need to be resolved. In my various messing with things, `mapca` is not generating the correct output version info. `mapca._version=='0+unknown'`

When I run `pip install -e .'[all]'` it generates a new `_version.py` file but something isn't working.

**Comment by eurunuela** [comment]
Okay, I just realized both the relative import and the versioning issues were very silly mistakes.

I noticed we couldn't just remove the dot from the relative import, because it would be trying to import the `mapca/` folder. Instead, we had to aim for the `mapca.py` in that folder: `import mapca.mapca`. Like I said, a silly mistake.

Regarding the versioning, a similar mistake was made. When importing `__version__` we were targeting `mapca` and not the `_version.py` file, which is the one that actually contains the version.

Anyway, those two issues are now fixed. I will approve the PR and will let you merge if you think it's ready.

**Review by eurunuela — APPROVED** [review]

**Pull request merged**
