### PR TITLE
Allow utils._subsampling to accept ndarray

### PR DESCRIPTION
**Pull request by notZaki**
The current subsampling function only works for 3d arrays. This PR allows it to work for arbitrary number of dimensions and brings us closer to supporting 2D data as inputs (#5).

Notes:

- The function returns a view, so it is possible to mutate the input data
  + It doesn't look like the current code is doing any mutating/in-place operations, but we could return a copy to be safe

### CODE REVIEW

**Comment by tsalo** [comment]
The subsampling is performed across voxels though, right? So would subsampling a flattened SxT array really be equivalent to subsampling an XxYxZxT array?

**Comment by notZaki** [comment]
Subsampling a flattened array would not be equal to subsampling the original array. This is why the PR doesn't use flattening.

**Comment by eurunuela** [comment]
I would like to check how the original code does the subsampling for 2D. The original GIFT code supports 1D, 2D and 3D data for maPCA. However, we only took the 3D part for `tedana`. Maybe we should translate the 1D and 2D options directly from GIFT and then work on optimizing the code.

What do you guys think?

**Comment by notZaki** [comment]
The original GIFT implementation has additional if-statements to support 1D and 2D data: https://github.com/trendscenter/gift/blob/8f22c6078071f93bd5972ae37df3742f17631e9f/GroupICATv4.0c/icatb/icatb_estimate_dimension.m#L379-L396
In modern matlab, the [`downsample`](https://www.mathworks.com/help/signal/ref/downsample.html) could've been used as an alternative.

I'm not sure what the advantage would be of translating the GIFT code vs using the proposed slices.

**Comment by eurunuela** [comment]
> I'm not sure what the advantage would be of translating the GIFT code vs using the proposed slices.

The slices approach you proposed is much simpler imo. We could check if both approaches do the same and then stick to the slices one for simplicity.

**Review by eurunuela — APPROVED** [review]
Thank you @notZaki !

**Comment by eurunuela** [comment]
@tsalo are you okay with merging this PR?

**Comment by tsalo** [comment]
Sorry for the massive delay! Merging now.

**Pull request merged**
