### PR TITLE
[REF] Replace parzen window function with one from scipy

### PR DESCRIPTION
**Pull request by notZaki**
It looks like [`scipy.signal.windows.parzen`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.parzen.html) has the same functionality as `utils._parzen_win`. This PR makes the substitution.

The tests are still there to show that the replacement has the same output values. They could be removed.

This can be considered once the integration tests are up and running.

### CODE REVIEW

**Comment by eurunuela** [comment]
This is great. Thank you @notZaki !

**Comment by eurunuela** [comment]
@notZaki could you please push an empty commit to rerun the tests? Let's see if the integration test passes.

**Review by eurunuela — APPROVED** [review]
I'm happy with the changes. Thank you @notZaki !

**Comment by eurunuela** [comment]
@tsalo are you okay with merging this PR?

**Comment by tsalo** [comment]
Sorry sorry. Everything looks great. Merging now.

**Pull request merged**
